### ISSUE TITLE
How to configure tabnine pro?

### ISSUE THREAD

**Issue by lougreenwood** [aca/completion-tabnine#7]
Hi :)

How can I add my tabnine pro license when using this? I don't find any documentation on how to config tabnine cli or the expected format of the json file. Is this within the scope of this add-on?

**Comment by ricmatsui** [comment]
@lougreenwood You can type `TabNine::config` in any buffer with the source enabled and it should open the settings page in your default browser with an option to enter your license key.

**Comment by aca** [comment]
Sorry for the slow response. But the community seems to be moving to nvim-cmp instead of completion-nvim (me too).

 Please check this projects.
- https://github.com/hrsh7th/nvim-cmp
- https://github.com/tzachar/cmp-tabnine
